import fs from "fs";
import path from "path";
import { readIndex, readJSON, constraintPath, decisionPath } from "../store.js";
import type { Constraint, Decision } from "../types.js";

function buildMarkdownPrompt(constraints: Constraint[], decisions: Decision[]): string {
  let md = `# Octa Architectural Governance

You are operating in a codebase strictly governed by Octa.
You must adhere to the following architectural decisions and constraints at all times.
Do not suggest or generate code that violates these rules.

## 🚨 Architectural Constraints

These rules are actively enforced by CI/CD. Violations will break the build.
`;

  if (constraints.length === 0) {
    md += "\n*No constraints defined yet.*\n";
  }

  for (const c of constraints) {
    const risk = c.severity === "hard" ? "HARD CONSTRAINT" : "SOFT CONSTRAINT";
    md += `\n### [${risk}] ${c.id}\n`;
    md += `- **Rule**: ${c.rule}\n`;
    md += `- **Pattern**: \`${c.pattern}\`\n`;
    if (c.recommendation) {
      md += `- **Guidance**: ${c.recommendation}\n`;
    }
  }

  md += `\n## 📚 Architectural Decisions (ADRs)\n\n`;
  md += `These are historical context on why the system is built this way. Respect these design choices.\n`;

  if (decisions.length === 0) {
    md += "\n*No decisions defined yet.*\n";
  }

  for (const d of decisions) {
    if (!d.history || d.history.length === 0) continue;
    const latest = d.history[d.history.length - 1];
    if (latest?.status === "active") {
      md += `\n### ${d.id}: ${d.title}\n`;
      md += `- **Choice**: ${latest.choice}\n`;
      md += `- **Reason**: ${latest.reason}\n`;
      if (d.patterns && d.patterns.length > 0) {
        md += `- **Anchors**: \`${d.patterns.join(", ")}\`\n`;
      }
      if (d.supersedes && d.supersedes.length > 0) {
        md += `- **Supersedes**: ${d.supersedes.join(", ")}\n`;
      }
    }
  }

  md += `\n---\n*Auto-generated by Octa. Do not edit manually.*`;
  return md;
}

export async function sync(silent = false) {
  if (!silent) console.log("🤖 Compiling Octa intent graph for AI assistants...");

  const index = readIndex();
  
  const constraints = index.constraints
    .map((id: string) => readJSON(constraintPath(id)))
    .filter(Boolean) as Constraint[];

  const decisions = index.decisions
    .map((id: string) => readJSON(decisionPath(id)))
    .filter(Boolean) as Decision[];

  const mdPrompt = buildMarkdownPrompt(constraints, decisions);

  // 1. Cursor Integration
  const cursorRulesPath = path.join(process.cwd(), ".cursorrules");
  fs.writeFileSync(cursorRulesPath, mdPrompt);

  // 2. GitHub Copilot Integration
  const githubDir = path.join(process.cwd(), ".github");
  if (!fs.existsSync(githubDir)) {
    fs.mkdirSync(githubDir, { recursive: true });
  }
  const copilotPath = path.join(githubDir, "copilot-instructions.md");
  fs.writeFileSync(copilotPath, mdPrompt);

  if (!silent) {
    console.log("✔ Injected constraints into .cursorrules");
    console.log("✔ Injected constraints into .github/copilot-instructions.md");
    console.log("🎉 AI Assistants are now perfectly synced with your architecture!");
  }
}
