name: Octa Architecture Check

on:
  pull_request:
  push:

jobs:
  octa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Octa validation
        run: npm run octa ci
